packaging_format = 2

id = "glitchsoc"
name = "Glitch-Soc"
description.en = "Libre and federated social network, fork of Mastodon"
description.fr = "Réseau social libre et fédéré, scission de Mastodon"

version = "2023.06.19~ynh2"

maintainers = ["Tagada"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://glitch-soc.github.io/docs/"
code = "https://github.com/glitch-soc/mastodon"
cpe = "???" # XXX: No CPE yet... The CPE may be obtained by searching here: https://nvd.nist.gov/products/cpe/search
fund = "???" # XXX: Nothing yet...

[integration]
yunohost = ">= 11.1"
architectures = "all"
multi_instance = true
ldap = true
sso = true
disk = "2G"
ram.build = "4G"
ram.runtime = "1G"

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"
    full_domain = true

    [install.admin]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "user"

    [install.init_main_permission]
    help.en = "visitors group is needed for federation."
    help.fr = "Le groupe visitors est nécessaire pour la fédération."
    type = "group"
    default = "visitors"

    [install.init_api_permission]
    help.en = "visitors group is needed to be able to use thrid party clients."
    help.fr = "Le groupe visitors est nécessaire pour pouvoir utiliser des clients tiers."
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "string"
    choices = ["en_EN", "fr_FR"]
    default = "fr_FR"

[resources]
        [resources.sources.main]
        url = "https://github.com/glitch-soc/mastodon/archive/eba3411bfa40cbb36205f58a36e34c446fed0ffa.tar.gz"
        sha256 = "7b49f8829f219a0310fefc9eac91f1f00383c6df09413fe085d411758774ce15"

        autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    api.url = "/api"
    api.allowed = "visitors"
    api.auth_header = false
    api.show_tile = false
    api.protected = true

    [resources.ports]
    web.default = 3000
    stream.default = 4000

    [resources.apt]
    packages = "imagemagick, ffmpeg, libpq-dev, libxml2-dev, libxslt1-dev, file, git-core, g++, libprotobuf-dev, protobuf-compiler, pkg-config, gcc, autoconf, bison, build-essential, libssl-dev, libyaml-dev, libreadline6-dev, zlib1g-dev, libncurses5-dev, libffi-dev, libgdbm6, libgdbm-dev, redis-server, redis-tools, postgresql, postgresql-contrib, libidn11-dev, libicu-dev, libjemalloc-dev, curl, apt-transport-https"

        [resources.apt.extras.yarn]
        repo = "deb https://dl.yarnpkg.com/debian/ stable main"
        key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
        packages = "yarn"

    [resources.database]
    type = "postgresql"
